sudo: required
services:
  - docker

before_install:
  - docker build -t yokesim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yokesim/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-184667795628"
  path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
